/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.sql.Connection;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author GTB Student
 */
public class addemployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form addemployee
     */
    public addemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Add Admin / Employee");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Address");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("City");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Country");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "India", "USA", "UK", "China", "Japan", "Australia", "Others" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gender");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Phone");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Email ID");

        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Username");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Date of Birth");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Admin", "Employee" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone", "Username"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("User Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(53, 53, 53)
                                .addComponent(jRadioButton2))
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(212, 212, 212)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(208, 208, 208)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton3)
                        .addGap(283, 283, 283)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setBounds(0, 0, 1278, 743);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        boolean flag=true;
        
        if(jTextField1.getText().length()<2)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter proper name");
            flag=false;
        }
        else if(jTextArea1.getText().length()<2)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter proper address");
            flag=false;
        }
        else if(jTextField5.getText().length()<2)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter proper city");
            flag=false;
        }
        else if(jComboBox1.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please choose country");
            flag=false;
        }
        else if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false)
        {
            JOptionPane.showMessageDialog(rootPane, "Please choose gender");
            flag=false;
        }
        else if(jFormattedTextField1.getText().length()<10)
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter phone");
            flag=false;
        }
        else if(jTextField2.getText().length()<2 || !jTextField2.getText().contains("@") || !jTextField2.getText().contains("."))
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter proper email id");
            flag=false;
        }
        else if(jComboBox2.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Please choose user type");
            flag=false;
        }
        
        String path = "jdbc:mysql://localhost/inventorydb";
        try
        {
            Connection myconn = DriverManager.getConnection(path, "mydbuser","123");
            try
            {
                if(flag==true)
                {
                    String q="insert into addemp values(?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement myst = myconn.prepareStatement(q);
                    myst.setString(1, jTextField1.getText());
                    myst.setString(2, jTextArea1.getText());
                    myst.setString(3, jTextField5.getText());
                    myst.setString(4, jComboBox1.getSelectedItem().toString());
                    if(jRadioButton1.isSelected())
                    {
                        myst.setString(5, "Male");
                    }
                    else if(jRadioButton2.isSelected())
                    {
                        myst.setString(5, jRadioButton2.getText());
                    }
                    myst.setString(6, jFormattedTextField1.getText());
                    myst.setString(7, jTextField2.getText());
                    myst.setString(8, jTextField7.getText());
                    myst.setString(9, jPasswordField1.getText());
                    myst.setString(10, jComboBox2.getSelectedItem().toString());
                    
                    SimpleDateFormat myformat= new SimpleDateFormat("yyyy-MM-dd");
                    
                    String dob = myformat.format(jDateChooser2.getDate());
                    
                    myst.setString(11, dob);
                    int res = myst.executeUpdate();

                    if(res>0)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Employee added successfully");
                        clearfields();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Employee not added successfully");
                    }
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            }
            finally
            {
                myconn.close();
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    void clearfields()
    {
        jTextField1.setText(null);
        jTextArea1.setText(null);
        jTextField5.setText(null);
        jComboBox1.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        jTextField2.setText(null);
        jTextField7.setText(null);
        jPasswordField1.setText(null);
        jComboBox2.setSelectedIndex(0);
        jDateChooser2.setDate(null);
        jFormattedTextField1.setText(null);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String path="jdbc:mysql://localhost/inventorydb";
        try
        {
            Connection myconn = DriverManager.getConnection(path,"mydbuser","123");
            try
            {
                String q="select * from addemp where phone=?";
                PreparedStatement myst = myconn.prepareStatement(q);
                myst.setString(1, jFormattedTextField1.getText());
              
                ResultSet res = myst.executeQuery();
                if(res.next())
                {
                    jTextField1.setText(res.getString("name"));
                    jTextArea1.setText(res.getString("address"));
                    jTextField5.setText(res.getString("city"));
                    jComboBox1.setSelectedItem(res.getString("country"));
                    if(res.getString("gender").equalsIgnoreCase("male"))
                    {
                        jRadioButton1.setSelected(true);
                    }
                    else
                    {
                        jRadioButton2.setSelected(true);
                    }
                    jTextField2.setText(res.getString("emailid"));
                    jTextField7.setText(res.getString("username"));
                    jPasswordField1.setText(res.getString("password"));
                    jComboBox2.setSelectedItem(res.getString("usertype"));
                }
                else
                {
                   JOptionPane.showMessageDialog(rootPane, "Wrong phone number"); 
                   clearfields();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage()); 
            }
            finally
            {
                myconn.close();
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String path="jdbc:mysql://localhost/inventorydb";
        try
        {
            Connection myconn = DriverManager.getConnection(path,"mydbuser","123");
            try
            {
                String q="select * from addemp where name like ?";
                PreparedStatement myst = myconn.prepareStatement(q);
                myst.setString(1, "%" + jTextField1.getText() + "%");
                ResultSet res = myst.executeQuery();
                DefaultTableModel mymodel = (DefaultTableModel)jTable1.getModel();
                mymodel.setRowCount(0);
                while(res.next())
                {
                    String nm = res.getString("name");
                    String add = res.getString("address");
                    String ph = res.getString("phone");
                    String un = res.getString("username");
                    Object myrow[] = {nm,add,ph,un};
                    mymodel.addRow(myrow);
                }
                if(jTable1.getRowCount()==0)
                {
                   JOptionPane.showMessageDialog(rootPane, "No records found"); 
                   clearfields();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage()); 
            }
            finally
            {
                myconn.close();
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       String un = jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();
        String path="jdbc:mysql://localhost/inventorydb";
        try
        {
            Connection myconn = DriverManager.getConnection(path,"mydbuser","123");
            try
            {
                String q="select * from addemp where username=?";
                PreparedStatement myst = myconn.prepareStatement(q);
                myst.setString(1, un);
              
                ResultSet res = myst.executeQuery();
                if(res.next())
                {
                    jTextField1.setText(res.getString("name"));
                    jTextArea1.setText(res.getString("address"));
                    jTextField5.setText(res.getString("city"));
                    jComboBox1.setSelectedItem(res.getString("country"));
                    if(res.getString("gender").equalsIgnoreCase("male"))
                    {
                        jRadioButton1.setSelected(true);
                    }
                    else
                    {
                        jRadioButton2.setSelected(true);
                    }
                    jTextField2.setText(res.getString("emailid"));
                    jFormattedTextField1.setText(res.getString("phone"));
                    jTextField7.setText(res.getString("username"));
                    jPasswordField1.setText(res.getString("password"));
                    jComboBox2.setSelectedItem(res.getString("usertype"));
                    jDateChooser2.setDate(res.getDate("dob"));
                }
                else
                {
                   JOptionPane.showMessageDialog(rootPane, "Wrong phone number"); 
                   clearfields();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query" + e.getMessage()); 
            }
            finally
            {
                myconn.close();
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + e.getMessage());
        }
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String path = "jdbc:mysql://localhost/inventorydb";
        try
        {
            Connection myconn = DriverManager.getConnection(path, "mydbuser","123");
            try
            {
                    String q="update addemp set name=?,address=?,city=?,country=?,gender=?,phone=?,emailid=?,password=?,usertype=?,dob=? where username=?";
                    PreparedStatement myst = myconn.prepareStatement(q);
                    myst.setString(1, jTextField1.getText());
                    myst.setString(2, jTextArea1.getText());
                    myst.setString(3, jTextField5.getText());
                    myst.setString(4, jComboBox1.getSelectedItem().toString());
                    if(jRadioButton1.isSelected())
                    {
                        myst.setString(5, "Male");
                    }
                    else if(jRadioButton2.isSelected())
                    {
                        myst.setString(5, jRadioButton2.getText());
                    }
                    myst.setString(6, jFormattedTextField1.getText());
                    myst.setString(7, jTextField2.getText());
   
                    myst.setString(8, jPasswordField1.getText());
                    myst.setString(9, jComboBox2.getSelectedItem().toString());
                    
                    SimpleDateFormat myformat= new SimpleDateFormat("yyyy-MM-dd");
                    String dob = myformat.format(jDateChooser2.getDate());

                    myst.setString(10, dob);
                    myst.setString(11, jTextField7.getText());

                    int res = myst.executeUpdate();

                    if(res>0)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Employee updated successfully");
                        clearfields();
                        DefaultTableModel mymodel =(DefaultTableModel) jTable1.getModel();
                        mymodel.setRowCount(0);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Employee not updated successfully");
                    }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            }
            finally
            {
                myconn.close();
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String path = "jdbc:mysql://localhost/inventorydb";
      
       if(jTextField7.getText().length()>0)
       {
            try
            {
                Connection myconn = DriverManager.getConnection(path, "mydbuser","123");
                try
                {
                    int choice = JOptionPane.showConfirmDialog(rootPane, "Are you sure to delete?","Confirm Deletion",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                    if(choice==JOptionPane.YES_OPTION)
                    {
                        String q="delete from addemp where username=?";
                        PreparedStatement myst = myconn.prepareStatement(q);
                        myst.setString(1, jTextField7.getText());
                        int res = myst.executeUpdate();
                        if(res>0)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Employee deleted successfully");
                            clearfields();
                            DefaultTableModel mymodel =(DefaultTableModel) jTable1.getModel();
                            mymodel.setRowCount(0);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Incorrect Username");
                        }
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
                }
                finally
                {
                    myconn.close();
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
            }
       }
       else
       {
           JOptionPane.showMessageDialog(rootPane, "Enter username to delete");
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
